### ISSUE TITLE
Is it possible to use multiple sound tracks in the same video?

### ISSUE THREAD

**Issue by archubbuck** [shotstack/python-demos#7]
Unsure of if this is currently available but I didn’t see an example in the repository.

**Comment by jeffski** [comment]
You can use the Audio Asset to add any kind of audio clip you want, see the SDK docs here: https://github.com/shotstack/shotstack-sdk-python#audioasset.

Audio assets work the same as video assets allowing you to place an audio clip (mp3) anywhere on the timeline and play for any amount of time. You can overlap multiple audio files using tracks and add as many as you like.
